name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install AWS CLI
        run: sudo apt-get update && sudo apt-get install -y awscli

      - name: Build, tag, and push image to ECR
        run: |
          # Define variables
          IMAGE_URI="026090559700.dkr.ecr.us-east-1.amazonaws.com/dev-app"

          # Build Docker image
          docker build -t $IMAGE_URI .

          # Tag image
          docker tag $IMAGE_URI:latest $IMAGE_URI:${{ github.sha }}

          # Push both tags
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:${{ github.sha }}

      - name: Upload static assets to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          # Define your S3 bucket name
          S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"

          aws s3 sync .next/static s3://${{ secrets.S3_BUCKET_NAME }}/_next/static --acl public-read --delete

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME }} \
            --force-new-deployment

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
